services:
  app-nginx:
    build:
      context: .
      dockerfile: docker/app/nginx-production.dockerfile
    container_name: app-nginx
    volumes:
      - ./main:/var/www/app
      - ./docker/certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - nginx-reverse-proxy
    networks:
      net:
        ipv4_address: 172.21.1.2

  app-php:
    build:
      context: .
      dockerfile: docker/app/php-fpm.dockerfile
    container_name: app-php
    volumes:
      - ./main:/var/www/app
      - ./docker/app/php-ini:/usr/local/etc/php/custom.d
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
    links:
      - mysql
#      - mailcatcher
    depends_on:
      - app-nginx
    networks:
      net:
        ipv4_address: 172.21.1.3

  queue-worker-php:
    build:
      context: .
      dockerfile: docker/queue-worker/php-fpm.dockerfile
    container_name: qw-php
    volumes:
      - ./main:/var/www/qw
    depends_on:
      - rabbitmq
    networks:
      net:
        ipv4_address: 172.21.1.4

  quasar:
    build:
      context: .
      dockerfile: docker/quasar/quasar.dockerfile
    container_name: quasar
    volumes:
      - ./docker/certbot/www:/var/www/certbot/:ro
      - ./docker/certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      net:
        ipv4_address: 172.21.1.6

#  cron:
#    build:
#      context: .
#      dockerfile: docker/cron/php-alpine.dockerfile
#    container_name: cron-php
#    volumes:
#      - ./main:/var/www/cron
#    networks:
#      net:
#        ipv4_address: 172.21.1.6

  centrifugo:
    image: centrifugo/centrifugo:v5.4
    container_name: centrifugo
    command: centrifugo -c config.json
    ports:
      - 8000:8000
    volumes:
      - ./docker/centrifugo:/centrifugo
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
    networks:
      net:
        ipv4_address: 172.21.1.249

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./docker/certbot/www/:/var/www/certbot/:rw
      - ./docker/certbot/conf/:/etc/letsencrypt/:rw
      - ./docker/certbot/log/letsencrypt/:/var/log/letsencrypt/:rw
    networks:
      net:
        ipv4_address: 172.21.1.250

  nginx-reverse-proxy:
    build:
      context: .
      dockerfile: docker/nginx-reverse-proxy/nginx-production.dockerfile
    container_name: nginx-reverse-proxy
    volumes:
      - ./docker/certbot/www:/var/www/certbot/:ro
      - ./docker/certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - 80:80
      - 443:443
    networks:
      net:
        ipv4_address: 172.21.1.251

  mysql:
    build:
      context: .
      dockerfile: docker/app/mysql.dockerfile
    container_name: app-mysql
    volumes:
      - ./Makefile:/Makefile
    ports:
      - 53307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fa_db
    networks:
      net:
        ipv4_address: 172.21.1.252

#  mailcatcher:
#    image: yappabe/mailcatcher
#    container_name: fa-mailcatcher
#    ports:
#      - 1025:1025
#      - 1080:1080
#    networks:
#      net:
#        ipv4_address: 172.21.1.253
#
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11.2-management
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    ports:
      # HTTP management UI
      - 15672:15672
    expose:
      # AMQP protocol port
      - 5672
    networks:
      net:
        ipv4_address: 172.21.1.254

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: "172.21.1.0/24"
